PR chrome extension
NCKU-CCS/fake-info-extension pull request #1
Opened 2021-03-30 10:13 UTC by williron3960

2021-04-04 10:07 UTC, grandq33769 reviewed
建議先使用 eslint 將所有語法怪怪的地方改過來。

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +    var requestURL = "http://127.0.0.1:8000/users/" + user_id + "/" + news_url + "/" + news_result  ;
`http://127.0.0.1:8000` 請使用變數代替，並將所有變數統一在另一個檔案中，另外 import 進來。

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +var urlPattern = '*://udn.com/*';
所有 `var` 請使用 `let` 或 `const` 代替，
`var` 在 ES6 後已經不建使用。
[[JS學徒特訓班] JavaScript ES6 : var, let, const 差異 | by Mio | 斜槓女紙 | Medium](https://medium.com/coding-girl-life/js-var-let-const-ef9895b4773b)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +                for (var i = 0; i < tabs.length; i++) {
這邊可以用 `map()` ? 
[JavaScript Demo: Array.map()](https://interactive-examples.mdn.mozilla.net/pages/js/array-map.html)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +chrome.runtime.onInstalled.addListener(function() {
這邊可以用 arrow function
[Arrow function expressions - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +    var user_id = response.user_id;
這邊應該可以用 Destructuring assignment

```
const {user_id, news_result, news_url} = response
```

[解構賦值 - JavaScript | MDN](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +    var dataJSON = {};
這邊可以寫成這樣嗎 ？

```
let dataJSON = {user_id, news_url, news_result}
```

[Object initializer - JavaScript | MDN](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Operators/Object_initializer)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +            url: "http://127.0.0.1:8000/users/" + user_id + "/" + news_url ,
http://127.0.0.1:8000 請使用變數代替，並將所有變數統一在另一個檔案中，另外 import 進來。

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +            url: "http://127.0.0.1:8000/users/" + user_id + "/" + news_url ,
請使用 string template 

`${HOST}/users/${user_id}/${news_url}`

[樣板字面值 - JavaScript | MDN](https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Template_literals)

2021-04-04 10:07 UTC, grandq33769 commented on extension/background.js
> +                user_id : user_id,
可以改成以下 
```
data: {
   user_id,
   news_url
}
```

2021-04-04 10:07 UTC, grandq33769 commented on extension/popup.js
> +      var url = tabs[0].url;
為什麼是 `tabs[0]` ?

2021-04-04 10:07 UTC, grandq33769 commented on extension/popup.js
> +      var data = {}
你這邊直接 assign 就好

```
let data = {
  url: url.toString(),
  title,
  user_id: user_id.toString(),
  ...
}
```

2021-04-04 10:07 UTC, grandq33769 commented on extension/popup.js
> +      var data = {}
你這邊直接 assign 就好

```
let data = {
  url: url.toString(),
  title,
  user_id: user_id.toString(),
  ...
}
```

2021-04-04 15:27 UTC, iknowright commented on .gitignore
> +sql_app/main.py
這些是 backend 的資料，如果沒有 ignore 的必要，需要把它清掉。

2021-04-04 15:29 UTC, iknowright commented on extension/background.js
> +            console.log("botton over.");
`button`, 文中有很多錯字, 建議使用 vscode extension 進行檢查。

[Code Spelling Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

2021-04-04 15:30 UTC, iknowright commented on extension/background.js
> +    function checkAccount3(){
checkAccount3 的 3 意義不明確

2021-04-04 15:33 UTC, iknowright commented on extension/popup.js
> +      data["user_email"] = user_email;
這段的 field 重複性高，直接 assign。

2021-04-04 15:46 UTC, iknowright commented
這邊列幾段重點需要修復的東西
1. 錯字，請參考 [vscode extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) 偵測文字錯誤
2. 註解時，`//` 後面需要有一個空白再寫入內容，如 `// xxxx`
3. 每一行 code 後面都不要有 trailing space (尾綴空白), 雖然 github 這邊看不到差異，但如果再某一行程式不小心新增一格空白，都會形成一次程式差異。具體的修正方式可以使用 [Trailing Spaces](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) 做一鍵清除。
---
架構問題：
在向 server 發送**真實**或**不真實**的請求，應該由 server 來判斷該**文章**是否已經回報過了。應該不是先問 server 有沒有發生過，再選擇要不要發送請求。白話來說，今天要向 server 新增一個回報，直接由 server 來告知你這次的請求是否成功 （回送 200), 如果已經重複傳送請求，讓 server 告知你這次的請求失敗，然後失敗原因是什麼（回傳 400， msg: News already in database) 。或者這麼說，不是 extension 去判斷，而是 server 去判斷。

2021-04-04 15:48 UTC, iknowright requested changes
請根據我們的留言一個一個修復相關的問題，如果有任何地方不明白或需要協助，也可以在 thread 底下留言。

2021-04-07 05:23 UTC, williron3960 commented on extension/popup.js
> +      var url = tabs[0].url;
tabs是chrome extension的內建api，tabs 參數有包含目前網頁的url跟title等等的資訊。

2021-04-07 13:42 UTC, williron3960 commented on extension/popup.js
> +      var data = {}
完成

2021-04-07 13:42 UTC, williron3960 commented on extension/popup.js
> +      data["user_email"] = user_email;
完成

2021-04-07 13:45 UTC, williron3960 commented on extension/background.js
> +    function checkAccount3(){
完成

2021-04-07 13:45 UTC, williron3960 commented on extension/background.js
> +var urlPattern = '*://udn.com/*';
完成

2021-04-07 13:49 UTC, williron3960 commented on extension/background.js
> +                user_id : user_id,
完成

2021-04-07 14:05 UTC, williron3960 commented on .gitignore
> +sql_app/main.py
完成

2021-04-08 07:16 UTC, williron3960 commented on extension/background.js
> +    var requestURL = "http://127.0.0.1:8000/users/" + user_id + "/" + news_url + "/" + news_result  ;
完成

2021-04-16 09:17 UTC, iknowright approved these changes
LGTM

2021-04-18 14:51 UTC, merged