UI improvement
NCKU-CCS/fake-info-extension pull request #3
Opened 2021-05-13 05:57 UTC by williron3960

2021-05-17 01:46 UTC, iknowright commented on extension/background.js
> +    let requestURL = "http://127.0.0.1:8000/users/" + user_id + "/" + news_url + "/" + news_result + "/" + comment ;
之前說過可以用 templete literal 寫會更整齊
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2021-05-17 01:47 UTC, iknowright commented on extension/popup.js
> +function foo (){
定義不明的 function, 請 rename

2021-05-17 01:47 UTC, iknowright commented on extension/popup.js
>  function  result_true() {
result_true result_false, 有很大的重複，issues 有說怎麼改了，要留意

2021-05-17 01:49 UTC, iknowright requested changes
在發 PR 時，可以點列式修正或新增的內容，讓 reviewer 快速掌握你修改的內容

2021-05-17 08:27 UTC, Darkborderman requested changes

2021-05-17 08:27 UTC, Darkborderman commented on extension/popup.js
> +          // alert("f+1");
這些註解可以刪掉了

2021-05-17 08:27 UTC, Darkborderman commented on extension/popup.js
> +          // alert("t+1");
這些註解可以刪掉了

2021-05-19 02:07 UTC, iknowright commented on extension/.eslintrc.js
> +exports = {
這裡有兩點：
這個 eslint 怎麼用？目前看來這個 eslint 是依照 react 去 lint 的，然後實際上跑會出錯
想問一下你是怎麼執行 eslint 的？

這邊需要寫 README 讓大家知道你的 linting 怎麼跑，詳細的內用（eslint 是要裝在哪裡，有沒有 vscode eslint 輔助，開發者要怎麼去 replicate 你的環境），也就是說 我今天拉下來你的 repo ，怎麼讓那個人很清楚了解怎麼執行~

最後，主要是這個 eslint 我這裡跑，是由 error, 還沒修正的。可能是執行上的不同。需要討論一下。

2021-05-19 02:09 UTC, iknowright commented on extension/popup.js
> +      $("#msgurl").text(tabs[0].url);
變數名稱有點亂，建議使用 camelCase 處理變數

請使用 vscode code spelling 套件檢查自己的變數名稱
可以上網查 naming convention javascript

2021-05-19 02:16 UTC, iknowright requested changes
總結：
1. eslint 處理有點不明確，我這裡有一些可以參考的東西：
* 如果要開發者自己系統先有 eslint, 要提醒他們 (README), 要安裝 eslint `npm i -g eslint`
* 目前 `.eslintrc.js` 與 extension 不相容（我執行不到，或不會執行）
* https://stackoverflow.com/questions/48584556/eslint-chrome-is-not-defined-no-undef

2. 錯字修正
* README 有錯字
* 還是有錯字，還是要一一排除

2021-05-19 02:17 UTC, williron3960 commented on extension/.eslintrc.js
> +exports = {
好的沒問題，主要是我也還在研究設定的細節，主要是extension有一些chrome api 比較特殊會被報錯，所以我待會找出修正方法後會再修正，然後會加入在README，感謝!

2021-05-19 03:03 UTC, iknowright commented on extension/.eslintrc.js
> +exports = {
https://stackoverflow.com/questions/48584556/eslint-chrome-is-not-defined-no-undef

這個有幫助

2021-05-19 15:15 UTC, iknowright commented on .eslintrc.json
> +        "plugin:react/recommended"
react 應該用不到，.jsx 也沒有用到，可以可以把不必要的刪掉

2021-05-19 15:18 UTC, iknowright approved these changes
LGTM, 修了差不多，改了也有一段了，可以先進，感謝

2021-05-20 05:28 UTC, merged

2021-05-20 05:56 UTC, iknowright commented
#2